In [1]:
import numpy as np
import pandas as pd
import yfinance as yf

In [3]:
tickers = pd.read_csv('../data/raw/ticker_data.csv').rename(columns={'Ticker symbol' : 'ticker'})
print(tickers.shape)
print(len(tickers.ticker.unique()))
tickers_str_modified = ""
for ticker in tickers.ticker.values:
    if (ticker.endswith('.B')):
        tickers_str_modified += (ticker[0:-2] + '-B.ST ')

tickers_str_modified

(607, 1)
607

'VOLV-B.ST ERIC-B.ST HM-B.ST SKA-B.ST ELUX-B.ST SECU-B.ST SKF-B.ST ASSA-B.ST NCC-B.ST PEAB-B.ST INVE-B.ST HUSQ-B.ST HEXA-B.ST TREL-B.ST SAAB-B.ST TEL2-B.ST GETI-B.ST RATO-B.ST NIBE-B.ST LUND-B.ST SCA-B.ST MTG-B.ST LOOM-B.ST SWEC-B.ST HOLM-B.ST AF-B.ST HPOL-B.ST BEIJ-B.ST EKTA-B.ST LIFCO-B.ST LATO-B.ST ELAN-B.ST ADDT-B.ST CLAS-B.ST ARJO-B.ST NOLA-B.ST MCOV-B.ST BALD-B.ST RECI-B.ST SRNKE-B.ST NEWA-B.ST CLA-B.ST ITAB-B.ST FOI-B.ST MMGR-B.ST THQN-B.ST BETS-B.ST PNDX-B.ST BEIA-B.ST LAGR-B.ST BERG-B.ST VBG-B.ST SWOL-B.ST OEM-B.ST BRG-B.ST ANOD-B.ST DURC-B.ST MSON-B.ST VSSAB-B.ST KABE-B.ST ATRLJ-B.ST SKIS-B.ST ALIF-B.ST REJL-B.ST CAT-B.ST XANO-B.ST POOL-B.ST WALL-B.ST DCAR-B.ST NET-B.ST CONS-B.ST SBB-B.ST PROF-B.ST BTS-B.ST FING-B.ST STORY-B.ST MIDW-B.ST EOLU-B.ST SECT-B.ST PENG-B.ST PRIC-B.ST FMM-B.ST AGES-B.ST CCOR-B.ST PLAZ-B.ST ATVEXA-B.ST VIT-B.ST GHUS-B.ST LAMM-B.ST VRG-B.ST PREV-B.ST FOOT-B.ST INISS-B.ST BIOG-B.ST SOF-B.ST NIL-B.ST BIOA-B.ST ELOS-B.ST RAY-B.ST SVED-B.ST CBTT-B.ST MEAB-B.ST ZZ-B.ST STEF-B.ST OBOYA-B.ST NETI-B.ST AJA-B.ST SJR-B.ST IAR-B.ST SEAB-B.ST HEBA-B.ST STAR-B.ST TRIAN-B.ST DEVP-B.ST ALLG-B.ST MSAB-B.ST NTEK-B.ST EMPIR-B.ST BRIN-B.ST PRCO-B.ST TAGM-B.ST CRAD-B.ST PCOM-B.ST AYIMA-B.ST BACTI-B.ST K2A-B.ST HUBR-B.ST MACK-B.ST VERT-B.ST CLIME-B.ST ORTI-B.ST CLNK-B.ST MVIR-B.ST KINV-B.ST PALS-B.ST INTEG-B.ST FRAM-B.ST AVT-B.ST SALT-B.ST CLS-B.ST IZAFE-B.ST CI-B.ST AAP-B.ST TERRNT-B.ST NETM-B.ST EPIS-B.ST FRILL-B.ST BIOVIC-B.ST GAPW-B.ST TRIBO-B.ST TRAC-B.ST DEFL-B.ST DMYD-B.ST SIMRIS-B.ST CMOTEC-B.ST SVOL-B.ST LLSW-B.ST HIFA-B.ST COPP-B.ST IBT-B.ST HAV-B.ST '

In [4]:

data = yf.download(  
        # or pdr.get_data_yahoo(...
        # tickers list or string as well
        tickers = tickers_str_modified,

        # use "period" instead of start/end
        # valid periods: 1d,5d,1mo,3mo,6mo,1y,2y,5y,10y,ytd,max
        # (optional, default is '1mo')
        period = "10y",

        # fetch data by interval (including intraday if period < 60 days)
        # valid intervals: 1m,2m,5m,15m,30m,60m,90m,1h,1d,5d,1wk,1mo,3mo
        # (optional, default is '1d')
        interval = "1d",

        # group by ticker (to access via data['SPY'])
        # (optional, default is 'column')
        group_by = 'ticker',

        # adjust all OHLC automatically
        # (optional, default is False)
        auto_adjust = True,

        # download pre/post regular market hours data
        # (optional, default is False)
        prepost = True,

        # use threads for mass downloading? (True/False/Integer)
        # (optional, default is True)
        threads = True,

        # proxy URL scheme use use when downloading?
        # (optional, default is None)
        proxy = None
    )
data

[*********************100%***********************]  161 of 161 completed

3 Failed downloads:
- SEAB-B.ST: No data found, symbol may be delisted
- DCAR-B.ST: No data found for this date range, symbol may be delisted
- HUBR-B.ST: No data found, symbol may be delisted

             ANOD-B.ST                                              \
                  Open        High         Low       Close  Volume
Date
2009-12-01   14.907099   15.487895   14.842566   15.358829  159657
2009-12-02   15.423362   15.423362   14.907099   15.100698   48190
2009-12-03   14.842567   15.423363   14.842567   15.229765   68912
2009-12-04   14.971635   15.487898   14.971635   15.487898   53650
2009-12-07   15.487897   15.616963   15.229766   15.616963   80780
...                ...         ...         ...         ...     ...
2019-11-25  170.000000  172.000000  163.000000  164.000000   27187
2019-11-26  163.500000  169.500000  162.500000  164.000000   20505
2019-11-27  163.500000  163.500000  156.000000  158.000000  145624
2019-11-28  158.500000  160.500000  158.500000  160.500000   13115
2019-11-29  161.000000  161.000000  156.500000  160.500000  101482

           SIMRIS-B.ST                             ...   XANO-B.ST  \
                  Open  High   Low Close   Volume  ...        Open
Date                                               ...
2009-12-01         NaN   NaN   NaN   NaN      NaN  ...    2.151499
2009-12-02         NaN   NaN   NaN   NaN      NaN  ...    2.141979
2009-12-03         NaN   NaN   NaN   NaN      NaN  ...    2.199098
2009-12-04         NaN   NaN   NaN   NaN      NaN  ...    2.151499
2009-12-07         NaN   NaN   NaN   NaN      NaN  ...    2.180059
...                ...   ...   ...   ...      ...  ...         ...
2019-11-25        3.24  3.70  3.23  3.40  34494.0  ...  114.000000
2019-11-26        3.40  3.45  3.40  3.44    619.0  ...  113.000000
2019-11-27        3.44  3.64  3.44  3.44  18800.0  ...  114.000000
2019-11-28        3.45  3.45  3.35  3.42   4155.0  ...  112.000000
2019-11-29        3.40  3.64  3.35  3.35   8060.0  ...  113.000000

                                                          ELUX-B.ST  \
                  High         Low       Close   Volume        Open
Date
2009-12-01    2.189579    2.151499    2.189579   6706.0  121.545348
2009-12-02    2.141979    2.141979    2.141979   1578.0  120.702247
2009-12-03    2.208618    2.180059    2.180059  15249.0  122.177637
2009-12-04    2.189579    2.132459    2.132459  22460.0  117.751438
2009-12-07    2.265738    2.180059    2.265738  85318.0  121.756144
...                ...         ...         ...      ...         ...
2019-11-25  114.000000  111.000000  114.000000   2992.0  239.000000
2019-11-26  114.000000  112.000000  114.000000    995.0  243.000000
2019-11-27  114.000000  111.000000  112.000000   3624.0  243.699997
2019-11-28  114.000000  111.000000  113.000000   3312.0  240.899994
2019-11-29  115.000000  112.000000  114.000000   4079.0  244.100006


                  High         Low       Close   Volume
Date
2009-12-01  122.247922  119.859174  120.842773  2344601
2009-12-02  121.545334  119.367350  120.421211  2205378
2009-12-03  122.177637  118.454002  118.454002  2204255
2009-12-04  121.896621  117.610914  121.545334  2856622
2009-12-07  124.074642  121.194082  122.880257  1850196
...                ...         ...         ...      ...
2019-11-25  242.199997  238.800003  242.199997   814879
2019-11-26  243.199997  240.899994  243.000000   680325
2019-11-27  243.800003  240.899994  241.199997   656916
2019-11-28  242.000000  239.600006  242.000000   411279
2019-11-29  249.500000  243.600006  246.100006  1572005

[2513 rows x 808 columns]

In [6]:
data.to_pickle('../data/raw/swedish_stocks')