In [5]:
import pandas as pd
import numpy as np
import re
import os

In [6]:
data = pd.read_excel('./data/raw/financials_raw.xlsx', index_col = 0)

In [7]:
pd.DataFrame(data[data['Company name Latin alphabet'] == 'AB VOLVO'].columns)
data.rename(columns = {'Company name Latin alphabet' : 'Name'}, inplace = True)
data.drop('Consolidation code', axis = 1, inplace = True)
data

,Name,Country ISO code,City,"NACE Rev. 2, core code (4 digits)",Last avail. year,Operating revenue (Turnover)\nth USD 2019,Operating revenue (Turnover)\nth USD 2018,Operating revenue (Turnover)\nth USD 2017,Operating revenue (Turnover)\nth USD 2016,Operating revenue (Turnover)\nth USD 2015,...,Number of employees\n2019,Number of employees\n2018,Number of employees\n2017,Number of employees\n2016,Number of employees\n2015,Number of employees\n2014,Number of employees\n2013,Number of employees\n2012,Number of employees\n2011,Number of employees\n2010
1.0,AB VOLVO,SE,GOTEBORG,2910.0,2018.0,n.a.,43639044,40822124,33515371,37024334,...,n.a.,105175,87104,84039,88464,92822,95533,98717,98162,90409
2.0,TELEFONAKTIEBOLAGET LM ERICSSON,SE,STOCKHOLM,2630.0,2018.0,n.a.,23593154,25156554,24604952,29253151,...,n.a.,95359,100735,111464,116281,118055,114340,110255,104525,90261
3.0,HENNES & MAURITZ AB,SE,STOCKHOLM,4771.0,2018.0,n.a.,23159309,23887635,20963756,20781216,...,n.a.,123283,123178,114586,104634,93351,81099,72276,64874,59440
4.0,SKANSKA AB,SE,SOLNA,4120.0,2018.0,n.a.,19174427,19234527,16040806,18132049,...,n.a.,37450,40400,40642,48470,57866,57105,56618,52557,51645
5.0,AB ELECTROLUX,SE,STOCKHOLM,2751.0,2018.0,n.a.,13975124,14896808,13381960,14632618,...,n.a.,51798,56708,53889,55245,59481,60783,60590,57860,50920
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606.0,ASARINA PHARMA AB (PUBL),SE,SOLNA,7219.0,2018.0,n.a.,n.a.,204,n.a.,n.a.,...,n.a.,3,2,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.
607.0,NORDIC IRON ORE AB,SE,DANDERYD,729.0,2018.0,n.a.,n.a.,n.a.,11,12,...,n.a.,4,3,3,4,n.a.,7,4,n.a.,n.a.
608.0,EWPG HOLDING AB (PUBL),SE,STOCKHOLM,3511.0,2018.0,n.a.,n.a.,n.a.,n.a.,n.a.,...,n.a.,0,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.
609.0,TALKPOOL AG,CH,CHUR,6201.0,2019.0,n.a.,5078,5127,4921,n.a.,...,15,15,15,15,15,15,15,15,150,5
610.0,DDM HOLDING AG,CH,BAAR,6499.0,2019.0,n.a.,n.a.,n.a.,n.a.,n.a.,...,4,4,4,4,4,4,4,4,n.a.,n.a.

In [235]:
nice_data = pd.DataFrame(columns = list(['Year']) + list(data.columns[0:5]) + list(data.columns[5:126:10]))
nice_data.columns

Index(['Year', 'Name', 'Country ISO code', 'City',
       'NACE Rev. 2, core code (4 digits)', 'Last avail. year',
       'Operating revenue (Turnover)\nth USD 2019',
       'P/L before tax\nth USD 2019',
       'P/L for period [=Net income]\nth USD 2019', 'Cash flow\nth USD 2019',
       'Total assets\nth USD 2019', 'Shareholders funds\nth USD 2019',
       'Current ratio (x)\n2019', 'Profit margin (%)\n2019',
       'ROE using P/L before tax (%)\n2019',
       'ROCE using P/L before tax (%)\n2019',
       'Solvency ratio (Asset based) (%) \n2019', 'Number of employees\n2019'],
      dtype='object')

In [236]:
for column in nice_data.columns:
    nice_data.rename(columns = {column : re.sub('\n.*', '', column)}, inplace = True)

In [237]:
temp = nice_data
for year in range(2010,2020):
    temp.Year = year    
    temp.iloc[:, 1:6] = data.iloc[:, 0:5] 
    for cols in range(5, 125, 10):
        temp.iloc[:, int(6+(cols-5)/10)] = data.iloc[:, cols]
    nice_data = nice_data.append(temp)

     Year                             Name Country ISO code       City  \
0     NaN                         AB VOLVO              NaN        NaN
1     NaN  TELEFONAKTIEBOLAGET LM ERICSSON               SE   GOTEBORG
2     NaN              HENNES & MAURITZ AB               SE  STOCKHOLM
3     NaN                       SKANSKA AB               SE  STOCKHOLM
4     NaN                    AB ELECTROLUX               SE      SOLNA
..    ...                              ...              ...        ...
605   NaN         ASARINA PHARMA AB (PUBL)               SE  STOCKHOLM
606   NaN               NORDIC IRON ORE AB               SE      SOLNA
607   NaN           EWPG HOLDING AB (PUBL)               SE   DANDERYD
608   NaN                      TALKPOOL AG               SE  STOCKHOLM
609   NaN                   DDM HOLDING AG               CH       CHUR

     NACE Rev. 2, core code (4 digits)  Last avail. year  \
0                                  NaN               NaN
1                               2910.0            2018.0
2                               2630.0            2018.0
3                               4771.0            2018.0
4                               4120.0            2018.0
..                                 ...               ...
605                             7112.0            2017.0
606                             7219.0            2018.0
607                              729.0            2018.0
608                             3511.0            2018.0
609                             6201.0            2019.0

    Operating revenue (Turnover) P/L before tax P/L for period [=Net income]  \
0                            NaN            NaN                          NaN
1                           n.a.           n.a.                         n.a.
2                           n.a.           n.a.                         n.a.
3                           n.a.           n.a.                         n.a.
4                           n.a.           n.a.                         n.a.
..                           ...            ...                          ...
605                         n.a.           n.a.                         n.a.
606                         n.a.           n.a.                         n.a.
607                         n.a.           n.a.                         n.a.
608                         n.a.           n.a.                         n.a.
609                         n.a.           n.a.                         n.a.

    Cash flow Total assets Shareholders funds Current ratio (x)  \
0         NaN          NaN                NaN               NaN
1        n.a.         n.a.               n.a.              n.a.
2        n.a.         n.a.               n.a.              n.a.
3        n.a.         n.a.               n.a.              n.a.
4        n.a.         n.a.               n.a.              n.a.
..        ...          ...                ...               ...
605      n.a.         n.a.               n.a.              n.a.
606      n.a.         n.a.               n.a.              n.a.
607      n.a.         n.a.               n.a.              n.a.
608      n.a.         n.a.               n.a.              n.a.
609      n.a.         n.a.               n.a.              n.a.

    Profit margin (%) ROE using P/L before tax (%)  \
0                 NaN                          NaN
1                n.a.                         n.a.
2                n.a.                         n.a.
3                n.a.                         n.a.
4                n.a.                         n.a.
..                ...                          ...
605              n.a.                         n.a.
606              n.a.                         n.a.
607              n.a.                         n.a.
608              n.a.                         n.a.
609              n.a.                         n.a.

    ROCE using P/L before tax (%) Solvency ratio (Asset based) (%)   \
0                             NaN                               NaN
1                            n.a.                              n.a.
2                            n.a.                              n.a.
3                            n.a.                              n.a.
4                            n.a.                              n.a.
..                            ...                               ...
605                          n.a.                              n.a.
606                          n.a.                              n.a.
607                          n.a.                              n.a.
608                          n.a.                              n.a.
609                          n.a.                              n.a.

    Number of employees
0                   NaN
1                  n.a.
2                  n.a.
3                  n.a.
4                  n.a.
..                  ...
605                n.a.
606                n.a.
607                n.a.
608                n.a.
609                  15

[610 rows x 18 columns]
     Year                             Name Country ISO code       City  \
0    2011                              NaN              NaN        NaN
1    2011                         AB VOLVO               SE   GOTEBORG
2    2011  TELEFONAKTIEBOLAGET LM ERICSSON               SE  STOCKHOLM
3    2011              HENNES & MAURITZ AB               SE  STOCKHOLM
4    2011                       SKANSKA AB               SE      SOLNA
..    ...                              ...              ...        ...
605  2011              PETROTARG AB (PUBL)               SE  STOCKHOLM
606  2011         ASARINA PHARMA AB (PUBL)               SE      SOLNA
607  2011               NORDIC IRON ORE AB               SE   DANDERYD
608  2011           EWPG HOLDING AB (PUBL)               SE  STOCKHOLM
609  2011                      TALKPOOL AG               CH       CHUR

     NACE Rev. 2, core code (4 digits)  Last avail. year  \
0                                  NaN               NaN
1                               2910.0            2018.0
2                               2630.0            2018.0
3                               4771.0            2018.0
4                               4120.0            2018.0
..                                 ...               ...
605                             7112.0            2017.0
606                             7219.0            2018.0
607                              729.0            2018.0
608                             3511.0            2018.0
609                             6201.0            2019.0

    Operating revenue (Turnover) P/L before tax P/L for period [=Net income]  \
0                            NaN            NaN                          NaN
1                           n.a.           n.a.                         n.a.
2                           n.a.           n.a.                         n.a.
3                           n.a.           n.a.                         n.a.
4                           n.a.           n.a.                         n.a.
..                           ...            ...                          ...
605                         n.a.           n.a.                         n.a.
606                         n.a.           n.a.                         n.a.
607                         n.a.           n.a.                         n.a.
608                         n.a.           n.a.                         n.a.
609                         n.a.           n.a.                         n.a.

    Cash flow Total assets Shareholders funds Current ratio (x)  \
0         NaN          NaN                NaN               NaN
1        n.a.         n.a.               n.a.              n.a.
2        n.a.         n.a.               n.a.              n.a.
3        n.a.         n.a.               n.a.              n.a.
4        n.a.         n.a.               n.a.              n.a.
..        ...          ...                ...               ...
605      n.a.         n.a.               n.a.              n.a.
606      n.a.         n.a.               n.a.              n.a.
607      n.a.         n.a.               n.a.              n.a.
608      n.a.         n.a.               n.a.              n.a.
609      n.a.         n.a.               n.a.              n.a.

    Profit margin (%) ROE using P/L before tax (%)  \
0                 NaN                          NaN
1                n.a.                         n.a.
2                n.a.                         n.a.
3                n.a.                         n.a.
4                n.a.                         n.a.
..                ...                          ...
605              n.a.                         n.a.
606              n.a.                         n.a.
607              n.a.                         n.a.
608              n.a.                         n.a.
609              n.a.                         n.a.

    ROCE using P/L before tax (%) Solvency ratio (Asset based) (%)   \
0                             NaN                               NaN
1                            n.a.                              n.a.
2                            n.a.                              n.a.
3                            n.a.                              n.a.
4                            n.a.                              n.a.
..                            ...                               ...
605                          n.a.                              n.a.
606                          n.a.                              n.a.
607                          n.a.                              n.a.
608                          n.a.                              n.a.
609                          n.a.                              n.a.

    Number of employees
0                   NaN
1                  n.a.
2                  n.a.
3                  n.a.
4                  n.a.
..                  ...
605                n.a.
606                n.a.
607                n.a.
608                n.a.
609                  15

[610 rows x 18 columns]
     Year                             Name Country ISO code       City  \
0    2012                              NaN              NaN        NaN
1    2012                         AB VOLVO               SE   GOTEBORG
2    2012  TELEFONAKTIEBOLAGET LM ERICSSON               SE  STOCKHOLM
3    2012              HENNES & MAURITZ AB               SE  STOCKHOLM
4    2012                       SKANSKA AB               SE      SOLNA
..    ...                              ...              ...        ...
605  2012              PETROTARG AB (PUBL)               SE  STOCKHOLM
606  2012         ASARINA PHARMA AB (PUBL)               SE      SOLNA
607  2012               NORDIC IRON ORE AB               SE   DANDERYD
608  2012           EWPG HOLDING AB (PUBL)               SE  STOCKHOLM
609  2012                      TALKPOOL AG               CH       CHUR

     NACE Rev. 2, core code (4 digits)  Last avail. year  \
0                                  NaN               NaN
1                               2910.0            2018.0
2                               2630.0            2018.0
3                               4771.0            2018.0
4                               4120.0            2018.0
..                                 ...               ...
605                             7112.0            2017.0
606                             7219.0            2018.0
607                              729.0            2018.0
608                             3511.0            2018.0
609                             6201.0            2019.0

    Operating revenue (Turnover) P/L before tax P/L for period [=Net income]  \
0                            NaN            NaN                          NaN
1                           n.a.           n.a.                         n.a.
2                           n.a.           n.a.                         n.a.
3                           n.a.           n.a.                         n.a.
4                           n.a.           n.a.                         n.a.
..                           ...            ...                          ...
605                         n.a.           n.a.                         n.a.
606                         n.a.           n.a.                         n.a.
607                         n.a.           n.a.                         n.a.
608                         n.a.           n.a.                         n.a.
609                         n.a.           n.a.                         n.a.

    Cash flow Total assets Shareholders funds Current ratio (x)  \
0         NaN          NaN                NaN               NaN
1        n.a.         n.a.               n.a.              n.a.
2        n.a.         n.a.               n.a.              n.a.
3        n.a.         n.a.               n.a.              n.a.
4        n.a.         n.a.               n.a.              n.a.
..        ...          ...                ...               ...
605      n.a.         n.a.               n.a.              n.a.
606      n.a.         n.a.               n.a.              n.a.
607      n.a.         n.a.               n.a.              n.a.
608      n.a.         n.a.               n.a.              n.a.
609      n.a.         n.a.               n.a.              n.a.

    Profit margin (%) ROE using P/L before tax (%)  \
0                 NaN                          NaN
1                n.a.                         n.a.
2                n.a.                         n.a.
3                n.a.                         n.a.
4                n.a.                         n.a.
..                ...                          ...
605              n.a.                         n.a.
606              n.a.                         n.a.
607              n.a.                         n.a.
608              n.a.                         n.a.
609              n.a.                         n.a.

    ROCE using P/L before tax (%) Solvency ratio (Asset based) (%)   \
0                             NaN                               NaN
1                            n.a.                              n.a.
2                            n.a.                              n.a.
3                            n.a.                              n.a.
4                            n.a.                              n.a.
..                            ...                               ...
605                          n.a.                              n.a.
606                          n.a.                              n.a.
607                          n.a.                              n.a.
608                          n.a.                              n.a.
609                          n.a.                              n.a.

    Number of employees
0                   NaN
1                  n.a.
2                  n.a.
3                  n.a.
4                  n.a.
..                  ...
605                n.a.
606                n.a.
607                n.a.
608                n.a.
609                  15

[610 rows x 18 columns]
     Year                             Name Country ISO code       City  \
0    2013                              NaN              NaN        NaN
1    2013                         AB VOLVO               SE   GOTEBORG
2    2013  TELEFONAKTIEBOLAGET LM ERICSSON               SE  STOCKHOLM
3    2013              HENNES & MAURITZ AB               SE  STOCKHOLM
4    2013                       SKANSKA AB               SE      SOLNA
..    ...                              ...              ...        ...
605  2013              PETROTARG AB (PUBL)               SE  STOCKHOLM
606  2013         ASARINA PHARMA AB (PUBL)               SE      SOLNA
607  2013               NORDIC IRON ORE AB               SE   DANDERYD
608  2013           EWPG HOLDING AB (PUBL)               SE  STOCKHOLM
609  2013                      TALKPOOL AG               CH       CHUR

     NACE Rev. 2, core code (4 digits)  Last avail. year  \
0                                  NaN               NaN
1                               2910.0            2018.0
2                               2630.0            2018.0
3                               4771.0            2018.0
4                               4120.0            2018.0
..                                 ...               ...
605                             7112.0            2017.0
606                             7219.0            2018.0
607                              729.0            2018.0
608                             3511.0            2018.0
609                             6201.0            2019.0

    Operating revenue (Turnover) P/L before tax P/L for period [=Net income]  \
0                            NaN            NaN                          NaN
1                           n.a.           n.a.                         n.a.
2                           n.a.           n.a.                         n.a.
3                           n.a.           n.a.                         n.a.
4                           n.a.           n.a.                         n.a.
..                           ...            ...                          ...
605                         n.a.           n.a.                         n.a.
606                         n.a.           n.a.                         n.a.
607                         n.a.           n.a.                         n.a.
608                         n.a.           n.a.                         n.a.
609                         n.a.           n.a.                         n.a.

    Cash flow Total assets Shareholders funds Current ratio (x)  \
0         NaN          NaN                NaN               NaN
1        n.a.         n.a.               n.a.              n.a.
2        n.a.         n.a.               n.a.              n.a.
3        n.a.         n.a.               n.a.              n.a.
4        n.a.         n.a.               n.a.              n.a.
..        ...          ...                ...               ...
605      n.a.         n.a.               n.a.              n.a.
606      n.a.         n.a.               n.a.              n.a.
607      n.a.         n.a.               n.a.              n.a.
608      n.a.         n.a.               n.a.              n.a.
609      n.a.         n.a.               n.a.              n.a.

    Profit margin (%) ROE using P/L before tax (%)  \
0                 NaN                          NaN
1                n.a.                         n.a.
2                n.a.                         n.a.
3                n.a.                         n.a.
4                n.a.                         n.a.
..                ...                          ...
605              n.a.                         n.a.
606              n.a.                         n.a.
607              n.a.                         n.a.
608              n.a.                         n.a.
609              n.a.                         n.a.

    ROCE using P/L before tax (%) Solvency ratio (Asset based) (%)   \
0                             NaN                               NaN
1                            n.a.                              n.a.
2                            n.a.                              n.a.
3                            n.a.                              n.a.
4                            n.a.                              n.a.
..                            ...                               ...
605                          n.a.                              n.a.
606                          n.a.                              n.a.
607                          n.a.                              n.a.
608                          n.a.                              n.a.
609                          n.a.                              n.a.

    Number of employees
0                   NaN
1                  n.a.
2                  n.a.
3                  n.a.
4                  n.a.
..                  ...
605                n.a.
606                n.a.
607                n.a.
608                n.a.
609                  15

[610 rows x 18 columns]

In [225]:
nice_data.iloc[:, 5:]

,Last avail. year,Operating revenue (Turnover),P/L before tax,P/L for period [=Net income],Cash flow,Total assets,Shareholders funds,Current ratio (x),Profit margin (%),ROE using P/L before tax (%),ROCE using P/L before tax (%),Solvency ratio (Asset based) (%),Number of employees
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2018.0,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.
2,2018.0,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.
3,2018.0,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.
4,2018.0,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.
...,...,...,...,...,...,...,...,...,...,...,...,...,...
605,2017.0,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.
606,2018.0,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.
607,2018.0,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.
608,2018.0,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.
609,2019.0,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,n.a.,15

Index(['Name', 'Country ISO code', 'City', 'NACE Rev. 2, core code (4 digits)',
       'Last avail. year', 'Operating revenue (Turnover)\nth USD 2019',
       'Operating revenue (Turnover)\nth USD 2018',
       'Operating revenue (Turnover)\nth USD 2017',
       'Operating revenue (Turnover)\nth USD 2016',
       'Operating revenue (Turnover)\nth USD 2015',
       ...
       'Number of employees\n2019', 'Number of employees\n2018',
       'Number of employees\n2017', 'Number of employees\n2016',
       'Number of employees\n2015', 'Number of employees\n2014',
       'Number of employees\n2013', 'Number of employees\n2012',
       'Number of employees\n2011', 'Number of employees\n2010'],
      dtype='object', length=125)